### PR TITLE
QU-75 added Lifecycle handling for InProcessJobs and scheduledJobs

### LINKED ISSUE #75: "JobsCommand did not shutdown before deinit" when run unit tests
### Steps to reproduce

I use the QUEUES package and try to understand how to use it. I have created a simple Job which fetches data from a remote server. I config vapor application with the following function 

```swift
// configures your application
public func configure(_ app: Application) throws {
    // uncomment to serve files from /Public folder
    // app.middleware.use(FileMiddleware(publicDirectory: app.directory.publicDirectory))

    app.databases.use(.sqlite(.file("db.sqlite")), as: .sqlite)
    
    try app.queues.use(.redis(url: "redis://127.0.0.1:6379"))

    //Register jobs
    let categoriesFetcherJob = FetcherJob()
    app.queues.add(categoriesFetcherJob)
    applyWPV2Migrations(app)
    
    try app.queues.startInProcessJobs(on: .default)
    // register routes
    try routes(app)
}
```

I dispatch Job from Controller like this:

```swift
    func index(req: Request) throws -> EventLoopFuture<[String: String]> {
        let jobPayload = CategoriesFetcherJobPayload(startPage: 1, categoriesPerPage: 10)
        return req.queue.dispatch(FetcherJob.self, jobPayload)
            .flatMap { (_) -> EventLoopFuture<[String: String]> in
                let res = ["status": "Fetching of remote categories was scheduled successfully"]
                return req.eventLoop.makeSucceededFuture(res)
        }
    }
```

The issue occurs when I run unit tests not necessarily related to JOB functionality:

```swift
    func testAssert() throws {
        let app = Application(.testing)
        defer {  app.shutdown() }
        try configure(app)
        XCTAssertTrue(true)
} 
```

After execution, I always hit assertion  `assert(self.didShutdown, "JobsCommand did not shutdown before deinit")`

**#6	0x0000000105535f34 in QueuesCommand.deinit at /queues/Sources/Queues/QueuesCommand.swift:164**

OR

            `assertionFailure("Command handler deinit when queue is not empty! Queue size: \(self.commandResponseQueue.count)")`

**#7	0x00000001053f0a07 in RedisCommandHandler.deinit at /RediStack/Sources/RediStack/ChannelHandlers/RedisCommandHandler.swift:43**

### Expected behavior

Tests do not crash

### Actual behavior

Hit assertion related to JOB but there is no way to shutdown it properly.

### Environment

```
 dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.14.0"),
        .package(url: "https://github.com/vapor/fluent.git", from: "4.0.0"),
        .package(url: "https://github.com/vapor/fluent-sqlite-driver.git", from: "4.0.0-rc.2"),
        .package(url: "https://github.com/vapor/queues-redis-driver.git", from: "1.0.0-rc.3"),
        // .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.8.0")
    ],

```
macOS 10.15.4

### PR DESCRIPTION
**Pull request by 3a4oT**
Try to fix #75

### CODE REVIEW

**Comment by 3a4oT** [comment]
To be honest now sure why there is `Swift access race`.

File: Sources/Queues/Application+Queues.swift [hunk 1]
```diff
@@ -21,14 +21,25 @@ extension Application {
...
 
         final class Storage {
+            enum QueuesType: String {
+                case `default` = "queues"
+                case inProcessJob = "inProcessJobsQueues"
+                case scheduledJobs = "scheduledJobsQueues"
+            }
             public var configuration: QueuesConfiguration
-            let command: QueuesCommand
+            private (set) var commands: [QueuesType: QueuesCommand]
```
Comment (jdmcd) [inline Sources/Queues/Application+Queues.swift:30]: Does this need to be a dictionary? Or can we just loop over the values and shut them down?

File: Sources/Queues/Application+Queues.swift [hunk 2]
```diff
@@ -21,14 +21,25 @@ extension Application {
...
             var driver: QueuesDriver?
 
             public init(_ application: Application) {
                 self.configuration = .init(logger: application.logger)
-                self.command = .init(application: application)
-                application.commands.use(self.command, as: "queues")
+                let command: QueuesCommand = .init(application: application)
```
Comment (jdmcd) [inline Sources/Queues/Application+Queues.swift:35]: The access race error is most likely caused by the lack of a `Lock` here

File: Sources/Queues/Application+Queues.swift (hunk 1 above)
Comment (3a4oT) [reply Sources/Queues/Application+Queues.swift:30]: The reason behind it was that I'm not sure about the purpose of three different `QueuesCommand` and whether we need a way to control/update each type. It definitely can be an array

File: Sources/Queues/Application+Queues.swift (hunk 2 above)
Comment (3a4oT) [reply Sources/Queues/Application+Queues.swift:35]: Thank's I have tried to add lock but it doesn't help. It can be related to `run` scheduled twice but I do not understand how that possible.

*QueueWorker*

```
 public func run() -> EventLoopFuture<Void> {
        self.queue.pop().flatMap { id in

```


*TestQueue*

```
    func pop() -> EventLoopFuture<JobIdentifier?> {
        return self.context.eventLoop.makeSucceededFuture(context.application.queues.test.queue.popLast())
    }
```

Not sure how but `run` seems to be executed twice.

File: Sources/Queues/Application+Queues.swift (hunk 1 above)
Comment (jdmcd) [reply Sources/Queues/Application+Queues.swift:30]: Gotcha, yeah let's leave it as an array

File: Sources/Queues/Application+Queues.swift (hunk 2 above)
Comment (jdmcd) [reply Sources/Queues/Application+Queues.swift:35]: What happens if we make the previous comment an array and then rerun?

**Comment by jdmcd** [comment]
@tanner0101 would love your input on this - there's an access race but I can't quite trace what the cause is

**Comment by 3a4oT** [comment]
For investigation purposes, I've added a lock for TestQueue methods and it seems to resolved original race access but instead, I faced with the new one and this time it reported on Vapor side (*Aplication+Routes.swift*)

```swift
    public var routes: Routes {
        if let existing = self.storage[RoutesKey.self] {
            return existing
        } else {
            let new = Routes()
            self.storage[RoutesKey.self] = new // race here
            return new
        }
    }

    private struct RoutesKey: StorageKey {
        typealias Value = Routes
    }
}

```

This race happens only if run all tests in the suite. Individual tests pass which is very confusing.

**Comment by jdmcd** [comment]
Thanks for doing that - we're definitely going to need @tanner0101's insight here :)

**Comment by tanner0101** [comment]
Looks like the race is happening in the test driver, so it might be innocuous. Merging this into a local branch so I can take a closer look.

**Comment by tanner0101** [comment]
Fixed the race conditions and merged in #80. Thanks @3a4oT !

**Comment by 3a4oT** [comment]
Thanks!
